###

GET http://localhost:3000/tododb

###

POST http://localhost:3000/tododb
Content-Type: application/json
Accept: application/json

{
    "task": "Belajar ExpressJs",
    "completed": true
}

###
DELETE http://localhost:3000/tododb/3
Content-Type: application/json
Accept: application/json

###
PUT http://localhost:3000/tododb/2
Content-Type: application/json
Accept: application/json

{
    "task": "Makan nasdang",
    "completed": true
}